#!/usr/bin/env python3
"""
generate_briefs_index.py — Generate a lightweight briefs index for fast scanning.

Parses OUTPUT_DIR/briefs.md and produces OUTPUT_DIR/briefs-index.md with one-line
summaries per entry. This enables pre-skill to load a compact index instead
of the full briefs file.

Usage
-----
    python .codex/skills/scripts/generate_briefs_index.py

Run from the repository root.
Optional flags:
    --verbose  Show each entry being processed
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from project_config import REPO_ROOT, get_path

BRIEFS_FILE = get_path("BRIEFS_FILE") or REPO_ROOT / "_output" / "briefs.md"
INDEX_FILE = BRIEFS_FILE.parent / "briefs-index.md"

# Match DONE entries: DONE | datetime | STARTED | datetime | skill | brief [| PLAN | id]
_DONE_RE = re.compile(
    r"^DONE\s*\|\s*([\d\-: UTC]+)\s*\|\s*STARTED\s*\|\s*([\d\-: UTC]+)\s*\|\s*(\S+)\s*\|\s*(.+?)(?:\s*\|\s*PLAN\s*\|\s*(\S+))?\s*$"
)

# Match orphaned STARTED entries: STARTED | datetime | skill | brief
_STARTED_RE = re.compile(
    r"^STARTED\s*\|\s*([\d\-: UTC]+)\s*\|\s*(\S+)\s*\|\s*(.+?)\s*$"
)


def truncate(text: str, max_len: int = 80) -> str:
    """Truncate text to max_len, appending ellipsis if needed."""
    text = text.strip()
    if len(text) <= max_len:
        return text
    return text[: max_len - 1] + "\u2026"


def parse_briefs(verbose: bool = False) -> list[dict]:
    """Parse briefs.md and return a list of entry dicts."""
    if not BRIEFS_FILE.is_file():
        print(f"ERROR: Briefs file not found: {BRIEFS_FILE}")
        return []

    text = BRIEFS_FILE.read_text(encoding="utf-8", errors="replace")
    entries = []

    for line in text.split("\n"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue

        # Try DONE format first
        m = _DONE_RE.match(line)
        if m:
            entries.append({
                "date": m.group(2).strip(),
                "skill": m.group(3).strip(),
                "brief": m.group(4).strip(),
                "status": "DONE",
                "plan_id": m.group(5).strip() if m.group(5) else "",
            })
            if verbose:
                print(f"  DONE: {m.group(3).strip()} — {truncate(m.group(4).strip(), 50)}")
            continue

        # Try orphaned STARTED format
        m = _STARTED_RE.match(line)
        if m:
            entries.append({
                "date": m.group(1).strip(),
                "skill": m.group(2).strip(),
                "brief": m.group(3).strip(),
                "status": "STARTED",
                "plan_id": "",
            })
            if verbose:
                print(f"  STARTED: {m.group(2).strip()} — {truncate(m.group(3).strip(), 50)}")
            continue


    return entries


def generate_index(verbose: bool = False) -> int:
    """Generate briefs-index.md. Returns count of indexed entries."""
    entries = parse_briefs(verbose=verbose)
    if not entries:
        print("No entries found in briefs.md")
        return 0

    lines = [
        "# Briefs Index",
        "",
        f"> Auto-generated by `generate_briefs_index.py`. {len(entries)} entries indexed.",
        "> Do not edit manually — regenerate with: `python .codex/skills/scripts/generate_briefs_index.py`",
        "",
        "| Date | Skill | Brief | Status | Plan |",
        "|------|-------|-------|--------|------|",
    ]

    for e in entries:
        brief_truncated = truncate(e["brief"])
        lines.append(
            f"| {e['date']} | {e['skill']} | {brief_truncated} | {e['status']} | {e['plan_id']} |"
        )

    lines.append("")
    INDEX_FILE.write_text("\n".join(lines), encoding="utf-8")

    print(f"Generated {INDEX_FILE.relative_to(REPO_ROOT)} with {len(entries)} entries.")
    return len(entries)


def main():
    parser = argparse.ArgumentParser(
        description="Generate a lightweight briefs index for fast scanning"
    )
    parser.add_argument(
        "--verbose", "-v", action="store_true",
        help="Show each entry being processed"
    )
    args = parser.parse_args()

    if sys.platform == "win32":
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    count = generate_index(verbose=args.verbose)
    if count == 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
