#!/usr/bin/env python3
"""
generate_essential_perspectives_summary.py — Extract Essential (P0) questions
from all 16 review perspective files and produce a single summary file.

Exit codes: 0 = success, 1 = partial (some files missing), 2 = script error.

Usage
-----
    python .codex/skills/scripts/generate_essential_perspectives_summary.py

Run from the repository root.
Optional flags:
    --output PATH   Override the output file path (default: _references/general/review-perspectives-essential-summary.md)
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
PERSPECTIVES_DIR = REPO_ROOT / "_references" / "general/review-perspectives"
DEFAULT_OUTPUT = REPO_ROOT / "_references" / "general/review-perspectives-essential-summary.md"

# Extract content between ## Essential and ## Deep-dive (or end of file)
ESSENTIAL_RE = re.compile(
    r"^## Essential\s*\n(.*?)(?=^## Deep-dive|\Z)",
    re.MULTILINE | re.DOTALL,
)


def extract_essential(filepath: Path) -> list[str]:
    """Extract Essential questions from a perspective file."""
    content = filepath.read_text(encoding="utf-8")
    match = ESSENTIAL_RE.search(content)
    if not match:
        return []
    lines = match.group(1).strip().splitlines()
    return [line.strip() for line in lines if line.strip().startswith("- [P")]


def get_title(filepath: Path) -> str:
    """Extract the H1 title from a perspective file."""
    content = filepath.read_text(encoding="utf-8")
    for line in content.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return filepath.stem.upper()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate essential perspectives summary."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Output file path",
    )
    args = parser.parse_args()

    if not PERSPECTIVES_DIR.exists():
        print(f"ERROR: Perspectives directory not found: {PERSPECTIVES_DIR}", file=sys.stderr)
        return 2

    perspective_files = sorted(PERSPECTIVES_DIR.glob("*.md"))
    if not perspective_files:
        print(f"ERROR: No .md files found in {PERSPECTIVES_DIR}", file=sys.stderr)
        return 2

    output_lines = [
        "# FRAMEWORK - ESSENTIAL REVIEW PERSPECTIVES SUMMARY",
        "",
        "> Auto-generated by `generate_essential_perspectives_summary.py`.",
        f"> {len(perspective_files)} perspectives indexed.",
        "> Do not edit manually — regenerate with: `python .codex/skills/scripts/generate_essential_perspectives_summary.py`",
        "",
        "---",
        "",
    ]

    total_questions = 0
    missing_count = 0

    for pfile in perspective_files:
        title = get_title(pfile)
        questions = extract_essential(pfile)

        if not questions:
            missing_count += 1
            output_lines.append(f"## {title}")
            output_lines.append("")
            output_lines.append("*No Essential questions found.*")
            output_lines.append("")
            continue

        output_lines.append(f"## {title}")
        output_lines.append("")
        for q in questions:
            output_lines.append(q)
            total_questions += 1
        output_lines.append("")

    # Add summary at the top (after header)
    summary_line = f"> Total: {total_questions} Essential questions across {len(perspective_files) - missing_count} perspectives."
    output_lines.insert(4, summary_line)

    args.output.write_text("\n".join(output_lines), encoding="utf-8")
    print(f"Generated {args.output} with {total_questions} Essential questions from {len(perspective_files)} perspectives.")

    return 1 if missing_count > 0 else 0


if __name__ == "__main__":
    sys.exit(main())
