#!/usr/bin/env python3
"""
generate_cheatsheet.py — Generate a skill quick reference for Codex skills from SKILL.md frontmatter.

Exit codes: 0 = success, 1 = no skills found, 2 = script error.

Scans all SKILL.md files, extracts metadata, and generates .codex/CHEATSHEET.md
grouped by category.

Usage
-----
    python .codex/skills/scripts/generate_cheatsheet.py

Run from the repository root.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
SKILLS_DIR = REPO_ROOT / ".codex" / "skills"
OUTPUT_FILE = REPO_ROOT / ".codex" / "CHEATSHEET.md"

_FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---", re.DOTALL)

CATEGORY_LABELS = {
    "planning": "Planning & Execution",
    "analysis": "Analysis & Review",
    "code": "Code & Tests",
    "utility": "Utilities",
}


def parse_frontmatter_light(text: str) -> dict:
    """Minimal frontmatter parser for cheatsheet generation."""
    match = _FRONTMATTER_RE.match(text)
    if not match:
        return {}

    result = {}
    in_metadata = False
    metadata = {}

    for line in match.group(1).split("\n"):
        stripped = line.strip()
        if not stripped:
            continue

        if not line.startswith(" ") and not line.startswith("\t"):
            in_metadata = False
            if ":" in stripped:
                key, _, value = stripped.partition(":")
                key = key.strip()
                value = value.strip().strip("\"'")
                if key == "metadata":
                    in_metadata = True
                else:
                    result[key] = value if value else ""
            continue

        if in_metadata and ":" in stripped:
            key, _, value = stripped.partition(":")
            key = key.strip()
            value = value.strip().strip("\"'")
            if value:
                metadata[key] = value

    if metadata:
        result["metadata"] = metadata
    return result


def generate_cheatsheet() -> int:
    """Generate CHEATSHEET.md. Returns number of skills documented."""
    skill_dirs = sorted(
        d for d in SKILLS_DIR.iterdir()
        if d.is_dir() and (d / "SKILL.md").exists()
    )

    skills_by_category: dict[str, list[dict]] = {}

    for skill_dir in skill_dirs:
        text = (skill_dir / "SKILL.md").read_text(encoding="utf-8")
        fm = parse_frontmatter_light(text)

        name = fm.get("name", skill_dir.name)
        description = fm.get("description", "")
        argument_hint = fm.get("argument-hint", "")
        metadata = fm.get("metadata", {})
        category = metadata.get("category", "utility")

        if category == "internal":
            continue

        # Truncate description to first sentence for table
        desc_short = description.split(". Use when")[0].rstrip(".")
        if len(desc_short) > 80:
            desc_short = desc_short[:77] + "..."

        entry = {
            "name": name,
            "description": desc_short,
            "argument_hint": argument_hint,
        }

        skills_by_category.setdefault(category, []).append(entry)

    if not skills_by_category:
        print("No skills found.")
        return 0

    lines = [
        "# Skill Cheat Sheet",
        "",
        "> Auto-generated by `generate_cheatsheet.py`. Do not edit manually.",
        "> Regenerate: `python .codex/skills/scripts/generate_cheatsheet.py`",
        "",
    ]

    total = 0
    for category in ["planning", "analysis", "code", "utility"]:
        skills = skills_by_category.get(category, [])
        if not skills:
            continue

        label = CATEGORY_LABELS.get(category, category.title())
        lines.append(f"## {label}")
        lines.append("")
        lines.append("| Skill | Description | Arguments |")
        lines.append("|-------|-------------|-----------|")

        for s in sorted(skills, key=lambda x: x["name"]):
            arg = f"`{s['argument_hint']}`" if s["argument_hint"] else "—"
            lines.append(f"| `${s['name']}` | {s['description']} | {arg} |")
            total += 1

        lines.append("")

    lines.append(f"*{total} skills available. Use `$pick-prompt` for interactive selection.*")
    lines.append("")

    OUTPUT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {OUTPUT_FILE.relative_to(REPO_ROOT)} with {total} skills.")
    return total


def main():
    if sys.platform == "win32":
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    count = generate_cheatsheet()
    sys.exit(0 if count > 0 else 1)


if __name__ == "__main__":
    main()
