#!/usr/bin/env python3
"""
reserve_id.py -- ID reservation for SEJA artifacts (single-writer assumed).

Reads _output/INDEX.md, finds the highest numeric ID across all entries
(including RESERVED rows), computes the next ID (zero-padded to 6 digits),
and appends a RESERVED row to INDEX.md. File writes use os.replace for
atomicity, but the read-then-write pattern assumes a single concurrent writer.

Usage
-----
    python .codex/skills/scripts/reserve_id.py --type advisory --title "Some title"
    python .codex/skills/scripts/reserve_id.py --type plan --title "Some title" --dry-run

Run from the repository root.
"""
from __future__ import annotations

import argparse
import os
import re
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

from project_config import REPO_ROOT, get_path

OUTPUT_DIR = get_path("OUTPUT_DIR") or REPO_ROOT / "_output"
INDEX_FILE = OUTPUT_DIR / "INDEX.md"

# Matches the ID column in table rows: captures numeric IDs (possibly zero-padded)
_ID_RE = re.compile(r"^\|[^|]*\|[^|]*\|\s*(\d+)\s*\|", re.MULTILINE)

INDEX_HEADER = """\
# Artifact Index

> Auto-generated by `generate_macro_index.py`. 0 artifacts indexed.
> Do not edit manually -- regenerate with: `python .codex/skills/scripts/generate_macro_index.py`

| Date | Type | ID | Title | Status | File |
|------|------|----|-------|--------|------|
"""


def _read_index() -> str | None:
    """Read INDEX.md if it exists, return contents or None."""
    if INDEX_FILE.is_file():
        return INDEX_FILE.read_text(encoding="utf-8")
    return None


def _extract_max_id(text: str) -> int:
    """Extract the highest numeric ID from all table rows."""
    ids = [int(m.group(1)) for m in _ID_RE.finditer(text)]
    return max(ids) if ids else 0


def _format_id(n: int) -> str:
    """Zero-pad an integer to 6 digits."""
    return str(n).zfill(6)


def _build_reserved_row(reserved_id: str, artifact_type: str, title: str) -> str:
    """Build a RESERVED table row."""
    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    return f"| {now_utc} | RESERVED | {reserved_id} | {artifact_type}: {title} | RESERVED | |"


def _write_index_atomic(content: str) -> None:
    """Write content to INDEX.md using write-then-rename for atomicity."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    # Write to a temp file in the same directory, then rename (atomic on same filesystem)
    fd, tmp_path = tempfile.mkstemp(
        dir=str(OUTPUT_DIR), prefix=".INDEX_", suffix=".tmp"
    )
    tmp = Path(tmp_path)
    try:
        # Close fd immediately so the file is not locked during rename
        os.close(fd)
        tmp.write_text(content, encoding="utf-8")
        # On Windows, use os.replace which handles open-file scenarios better
        os.replace(str(tmp), str(INDEX_FILE))
    except Exception:
        # Clean up temp file on failure
        if tmp.exists():
            try:
                tmp.unlink()
            except OSError:
                pass
        raise


def reserve(artifact_type: str, title: str, dry_run: bool = False) -> str:
    """Reserve the next ID and return it as a zero-padded string."""
    index_text = _read_index()

    if index_text is None:
        max_id = 0
        index_text = INDEX_HEADER
    else:
        max_id = _extract_max_id(index_text)

    next_id = _format_id(max_id + 1)

    if dry_run:
        return next_id

    reserved_row = _build_reserved_row(next_id, artifact_type, title)

    # Ensure the file ends with a newline before appending
    if not index_text.endswith("\n"):
        index_text += "\n"

    new_content = index_text + reserved_row + "\n"
    _write_index_atomic(new_content)

    return next_id


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Reserve the next artifact ID in INDEX.md"
    )
    parser.add_argument(
        "--type", required=True, dest="artifact_type",
        help="Artifact type (e.g., advisory, plan, check)",
    )
    parser.add_argument(
        "--title", required=True,
        help="Short descriptive title for the artifact",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print the next ID without writing to INDEX.md",
    )
    args = parser.parse_args()

    if sys.platform == "win32":
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[attr-defined]

    reserved_id = reserve(args.artifact_type, args.title, dry_run=args.dry_run)
    print(reserved_id)


if __name__ == "__main__":
    main()
