#!/usr/bin/env python3
"""
generate_skills_reference.py -- Generate the public-facing SEJA skills catalog.

Walks `.claude/skills/<name>/SKILL.md`, reuses the frontmatter parser and
internal-skill filter from `generate_skills_manifest.py`, and renders a
Markdown catalog grouped by `metadata.category` for the public docs.

Skills with no `metadata.category` are placed under an `Uncategorized`
section at the bottom. Internal lifecycle hooks (`pre-skill`, `post-skill`)
are excluded.

Usage
-----
    python .claude/skills/scripts/generate_skills_reference.py \
        --output seja-public/docs/reference/skills.md

Flags:
    --output <path>           Default: <framework-root>/seja-public/docs/
                              reference/skills.md. Use "-" for stdout.
    --framework-root <path>   Auto-detected by walking up to find .claude/.
    --check                   CI staleness detection. Exit 1 if drift.
    --fixed-date <ISO8601>    Testing only: pin the preamble timestamp.
    --verbose                 Progress logging to stderr.

Exit codes:
    0  success (or in sync with --check)
    1  drift detected in --check mode
    2  script error
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from generate_skills_manifest import INTERNAL_SKILLS, parse_frontmatter  # noqa: E402


UNCATEGORIZED_LABEL = "Uncategorized"


def _find_framework_root(start: Path | None = None) -> Path:
    candidate = (start or SCRIPTS_DIR).resolve()
    while candidate != candidate.parent:
        if (candidate / ".claude").is_dir():
            return candidate
        candidate = candidate.parent
    return Path.cwd()


def _escape_pipes(text: str) -> str:
    return text.replace("|", "\\|")


def collect_skills(framework_root: Path, verbose: bool = False) -> list[dict[str, str]]:
    """Return a list of skill metadata dicts for user-facing skills."""
    skills_dir = framework_root / ".claude" / "skills"
    if not skills_dir.is_dir():
        return []

    results: list[dict[str, str]] = []
    for skill_dir in sorted(skills_dir.iterdir()):
        if not skill_dir.is_dir():
            continue
        name = skill_dir.name
        if name in INTERNAL_SKILLS:
            if verbose:
                print(f"  skip (internal): {name}", file=sys.stderr)
            continue
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.is_file():
            if verbose:
                print(f"  skip (no SKILL.md): {name}", file=sys.stderr)
            continue
        fm = parse_frontmatter(skill_md) or {}
        category = fm.get("metadata.category", "").strip() or UNCATEGORIZED_LABEL
        if category == "internal":
            if verbose:
                print(f"  skip (internal category): {name}", file=sys.stderr)
            continue
        entry = {
            "name": fm.get("name", name),
            "description": fm.get("description", ""),
            "argument_hint": fm.get("argument-hint", ""),
            "category": category,
        }
        results.append(entry)
        if verbose:
            print(f"  added: {entry['name']} [{category}]", file=sys.stderr)

    return results


def render_skills_reference(
    skills: list[dict[str, str]],
    generated_at: str,
) -> str:
    """Compose the full Markdown skills catalog."""
    preamble = (
        "<!--\n"
        "This file is generated by .claude/skills/scripts/generate_skills_reference.py.\n"
        "Do not edit by hand. To regenerate:\n"
        "    python .claude/skills/scripts/generate_skills_reference.py \\\n"
        "        --output seja-public/docs/reference/skills.md\n"
        "-->\n\n"
        "# SEJA skills catalog\n\n"
        f"Generated {generated_at} from the seja-priv framework source. "
        "All skills listed below are invocable via `/<name>` in a Claude Code "
        "session. Internal lifecycle hooks (`pre-skill`, `post-skill`) are "
        "not listed.\n\n"
        "## Skills by category\n\n"
    )

    by_category: dict[str, list[dict[str, str]]] = {}
    for skill in skills:
        by_category.setdefault(skill["category"], []).append(skill)

    named = sorted(k for k in by_category if k != UNCATEGORIZED_LABEL)
    ordered = named + ([UNCATEGORIZED_LABEL] if UNCATEGORIZED_LABEL in by_category else [])

    sections: list[str] = []
    for category in ordered:
        entries = sorted(by_category[category], key=lambda s: s["name"])
        lines = [
            f"### {category}",
            "",
            "| Skill | Description | Argument hint |",
            "|---|---|---|",
        ]
        for entry in entries:
            skill_cell = f"`/{_escape_pipes(entry['name'])}`"
            desc_cell = _escape_pipes(entry["description"])
            hint_value = entry["argument_hint"]
            hint_cell = f"`{_escape_pipes(hint_value)}`" if hint_value else "-"
            lines.append(f"| {skill_cell} | {desc_cell} | {hint_cell} |")
        lines.append("")
        sections.append("\n".join(lines))

    return preamble + "\n".join(sections)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate the public-facing SEJA skills catalog",
    )
    parser.add_argument("--framework-root", default=None)
    parser.add_argument("--output", default=None)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--fixed-date", default=None)
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args(argv)

    framework_root = (
        Path(args.framework_root).resolve()
        if args.framework_root
        else _find_framework_root()
    )
    if not framework_root.is_dir():
        print(f"ERROR: framework root does not exist: {framework_root}", file=sys.stderr)
        return 2

    if args.verbose:
        print(f"framework_root: {framework_root}", file=sys.stderr)

    skills = collect_skills(framework_root, verbose=args.verbose)

    if args.fixed_date:
        generated_at = args.fixed_date
    else:
        generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    rendered = render_skills_reference(skills, generated_at)

    if args.check:
        if not args.output or args.output == "-":
            print("ERROR: --check requires an --output file path", file=sys.stderr)
            return 2
        output_path = Path(args.output).resolve()
        if not output_path.is_file():
            print(f"DRIFT: output file does not exist: {output_path}", file=sys.stderr)
            return 1
        on_disk = output_path.read_text(encoding="utf-8")
        if on_disk.replace("\r\n", "\n") == rendered.replace("\r\n", "\n"):
            if args.verbose:
                print(f"OK: {output_path} is up to date.", file=sys.stderr)
            return 0
        print(f"DRIFT: {output_path} differs from generator output", file=sys.stderr)
        return 1

    output_arg = args.output
    if output_arg is None:
        output_arg = str(framework_root / "seja-public" / "docs" / "reference" / "skills.md")

    if output_arg == "-":
        sys.stdout.write(rendered)
    else:
        output_path = Path(output_arg).resolve()
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(rendered, encoding="utf-8")
        if args.verbose:
            print(f"wrote: {output_path}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
