#!/usr/bin/env python3
"""
generate_briefs_index.py — Generate a lightweight briefs index for fast scanning.

Parses OUTPUT_DIR/briefs.md and produces OUTPUT_DIR/briefs-index.md with one-line
summaries per entry, sorted newest first (descending chronological order).
This enables pre-skill to load a compact index instead of the full briefs file.

Usage
-----
    python .claude/skills/scripts/generate_briefs_index.py

Run from the repository root.
Optional flags:
    --verbose  Show each entry being processed
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from project_config import REPO_ROOT, get_path

BRIEFS_FILE = get_path("BRIEFS_FILE") or REPO_ROOT / "_output" / "briefs.md"
INDEX_FILE = BRIEFS_FILE.parent / "briefs-index.md"

# Match the optional PLAN suffix at the end of a brief line
_PLAN_SUFFIX_RE = re.compile(r"\s*\|\s*PLAN\s*\|\s*(\S+)\s*$")


def truncate(text: str, max_len: int = 80) -> str:
    """Truncate text to max_len, appending ellipsis if needed."""
    text = text.strip()
    if len(text) <= max_len:
        return text
    return text[: max_len - 1] + "\u2026"


def _split_fields(line: str) -> list[str]:
    """Split a briefs line on ' | ' delimiters, returning stripped fields."""
    return [f.strip() for f in line.split(" | ")]


def _extract_skill(raw_skill: str) -> str:
    """Extract just the skill name from a field that may contain flags.

    E.g., 'advise --deep' -> 'advise', 'plan' -> 'plan'.
    """
    return raw_skill.split()[0] if raw_skill else raw_skill


def _extract_plan_id(text: str) -> tuple[str, str]:
    """Strip a trailing '| PLAN | <id>' suffix from text.

    Returns (text_without_suffix, plan_id). If no suffix, plan_id is ''.
    """
    m = _PLAN_SUFFIX_RE.search(text)
    if m:
        return text[: m.start()].strip(), m.group(1).strip()
    return text.strip(), ""


def _parse_done_line(fields: list[str]) -> dict | None:
    """Parse a DONE entry from split fields.

    Expected structure (minimum 6 fields):
      DONE | done_datetime | STARTED | start_datetime | skill [flags] | brief... [| PLAN | id]

    The brief may contain ' | ' so we rejoin fields[5:] and then strip the
    optional PLAN suffix from the end.
    """
    if len(fields) < 6:
        return None
    if fields[2] != "STARTED":
        return None

    raw_brief = " | ".join(fields[5:])
    brief, plan_id = _extract_plan_id(raw_brief)

    return {
        "date": fields[3],
        "skill": _extract_skill(fields[4]),
        "brief": brief,
        "status": "DONE",
        "plan_id": plan_id,
    }


def _parse_started_line(fields: list[str]) -> dict | None:
    """Parse a STARTED entry from split fields.

    Expected structure (minimum 4 fields):
      STARTED | datetime | skill [flags] | brief...

    The brief may contain ' | ' so we rejoin fields[3:].
    """
    if len(fields) < 4:
        return None

    raw_brief = " | ".join(fields[3:])

    return {
        "date": fields[1],
        "skill": _extract_skill(fields[2]),
        "brief": raw_brief.strip(),
        "status": "STARTED",
        "plan_id": "",
    }


def parse_briefs(verbose: bool = False) -> list[dict]:
    """Parse briefs.md and return a list of entry dicts."""
    if not BRIEFS_FILE.is_file():
        print(f"ERROR: Briefs file not found: {BRIEFS_FILE}")
        return []

    text = BRIEFS_FILE.read_text(encoding="utf-8", errors="replace")
    entries = []
    unparsed_count = 0

    for line_num, line in enumerate(text.split("\n"), start=1):
        line = line.strip()
        if not line or line.startswith("#"):
            continue

        fields = _split_fields(line)

        entry = None
        if fields[0] == "DONE":
            entry = _parse_done_line(fields)
        elif fields[0] == "STARTED":
            entry = _parse_started_line(fields)

        if entry:
            entries.append(entry)
            if verbose:
                print(f"  {entry['status']}: {entry['skill']} — {truncate(entry['brief'], 50)}")
        else:
            unparsed_count += 1
            print(f"WARNING: Unparseable line {line_num}: {line[:80]}")

    if unparsed_count > 0:
        print(f"{unparsed_count} unparseable line(s) found")

    return entries


def generate_index(verbose: bool = False) -> int:
    """Generate briefs-index.md. Returns count of indexed entries."""
    entries = parse_briefs(verbose=verbose)
    if not entries:
        print("No entries found in briefs.md")
        return 0

    lines = [
        "# Briefs Index",
        "",
        f"> Auto-generated by `generate_briefs_index.py`. {len(entries)} entries indexed (newest first).",
        "> Do not edit manually -- regenerate with: `python .claude/skills/scripts/generate_briefs_index.py`",
        "",
        "| Date | Skill | Brief | Status | Plan |",
        "|------|-------|-------|--------|------|",
    ]

    for e in entries:
        brief_truncated = truncate(e["brief"])
        lines.append(
            f"| {e['date']} | {e['skill']} | {brief_truncated} | {e['status']} | {e['plan_id']} |"
        )

    lines.append("")
    INDEX_FILE.write_text("\n".join(lines), encoding="utf-8")

    print(f"Generated {INDEX_FILE.relative_to(REPO_ROOT)} with {len(entries)} entries.")
    return len(entries)


def main():
    parser = argparse.ArgumentParser(
        description="Generate a lightweight briefs index for fast scanning"
    )
    parser.add_argument(
        "--verbose", "-v", action="store_true",
        help="Show each entry being processed"
    )
    args = parser.parse_args()

    if sys.platform == "win32":
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    count = generate_index(verbose=args.verbose)
    if count == 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
